import { useEffect, useState } from "react";
import { BottomNav, EmployeeHeader } from "../components/layout";
import { getAttendanceHistory, type Attendance } from "../lib/attendance";
import { scheduleStatusLabel } from "../lib/i18n";
import { useLanguage } from "../lib/language-context";

const scheduleColor = (value?: string): string => value === "LATE" || value === "MISSED_CLOCK_OUT" ? "bg-amber-50 text-amber-700" : value === "ON_TIME" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600";

export function HistoryPage(): JSX.Element {
  const { language, locale, t } = useLanguage();
  const [attendance, setAttendance] = useState<Attendance[]>([]);
  const [error, setError] = useState("");
  const time = (value: string | null): string => value ? new Intl.DateTimeFormat(locale, { hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "--";
  const date = (value: string): string => new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));
  useEffect(() => { getAttendanceHistory().then(setAttendance).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : t("unableToLoadHistory"))); }, [t]);
  return <div className="app-canvas mx-auto max-w-lg pb-28"><EmployeeHeader /><main className="px-5"><p className="text-sm font-medium text-slate-500">{t("yourWorkdays")}</p><h1 className="mt-1 text-2xl font-bold tracking-tight">{t("attendanceHistory")}</h1>{error && <p role="alert" className="mt-6 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{!error && attendance.length === 0 && <div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-6 text-center"><p className="font-bold">{t("noAttendanceYet")}</p><p className="mt-1 text-sm text-slate-500">{t("yourClockInsAppear")}</p></div>}<div className="mt-6 space-y-3">{attendance.map((record) => <article key={record.id} className="rounded-2xl border border-slate-100 p-5 shadow-card"><div className="flex items-start justify-between"><div><h2 className="font-bold">{date(record.workDate)}</h2><p className="mt-1 text-sm text-slate-500">{record.clockOutAt ? t("completedWorkday") : t("clockedIn")}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${record.clockOutAt ? "bg-slate-100 text-slate-600" : "bg-emerald-50 text-emerald-700"}`}>{record.clockOutAt ? t("completed") : t("active")}</span></div><div className="mt-4 grid grid-cols-2 border-t border-slate-100 pt-4 text-sm"><p className="text-slate-500">{t("clockIn")} <b className="block pt-1 text-slate-800">{time(record.clockInAt)}</b></p><p className="border-l border-slate-100 pl-4 text-slate-500">{t("clockOut")} <b className="block pt-1 text-slate-800">{time(record.clockOutAt)}</b></p></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><div><span className="block text-slate-400">{t("workingHours")}</span><strong className="text-sm text-slate-800">{record.totalWorkingHours ?? 0}h</strong></div><div><span className="block text-slate-400">{t("overtime")}</span><strong className="text-sm text-slate-800">{record.overtimeHours ?? 0}h</strong></div></div><span className={`mt-4 inline-block rounded-full px-3 py-1 text-xs font-bold uppercase tracking-wide ${scheduleColor(record.scheduleStatus)}`}>{scheduleStatusLabel(language, record.scheduleStatus)}</span></article>)}</div></main><BottomNav /></div>;
}
