import { useEffect, useState, type FormEvent } from "react";
import { DashboardShell, EmployeeHeader, BottomNav } from "../components/layout";
import { getProfile, updateProfile, type Profile } from "../lib/profile";
import { getSession } from "../lib/auth";

export function ProfilePage(): JSX.Element {
  const session = getSession();
  const [profile, setProfile] = useState<Profile | null>(null);
  const [form, setForm] = useState({ email: "", displayName: "", firstName: "", lastName: "", currentPassword: "", newPassword: "" });
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  useEffect(() => { getProfile().then((value) => { setProfile(value); setForm({ email: value.email, displayName: value.displayName ?? "", firstName: value.firstName, lastName: value.lastName, currentPassword: "", newPassword: "" }); }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : "Unable to load profile")); }, []);
  function setField(field: keyof typeof form, value: string): void { setForm((current) => ({ ...current, [field]: value })); }
  async function save(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); setError(""); setMessage(""); setSaving(true); try { const value = await updateProfile({ email: form.email, displayName: form.displayName || null, ...(profile?.role === "EMPLOYEE" ? { firstName: form.firstName, lastName: form.lastName } : {}), ...(form.newPassword ? { currentPassword: form.currentPassword, newPassword: form.newPassword } : {}) }); setProfile(value); setMessage("Profile updated"); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : "Unable to update profile"); } finally { setSaving(false); } }
  const fields = <form onSubmit={(event) => void save(event)} className="space-y-4 rounded-2xl bg-white p-5 shadow-card"><h2 className="text-lg font-bold">Profile details</h2><label className="block text-sm font-semibold text-slate-700">Email<input required type="email" value={form.email} onChange={(event) => setField("email", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label>{profile?.role === "EMPLOYEE" && <div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold text-slate-700">First name<input required value={form.firstName} onChange={(event) => setField("firstName", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Last name<input required value={form.lastName} onChange={(event) => setField("lastName", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label></div>}<label className="block text-sm font-semibold text-slate-700">Display name<input value={form.displayName} onChange={(event) => setField("displayName", event.target.value)} placeholder="Shown for admin accounts" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><div className="border-t border-slate-100 pt-4"><p className="text-sm font-bold">Change password</p><label className="mt-3 block text-sm font-semibold text-slate-700">Current password<input type="password" value={form.currentPassword} onChange={(event) => setField("currentPassword", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><label className="mt-3 block text-sm font-semibold text-slate-700">New password<input minLength={8} type="password" value={form.newPassword} onChange={(event) => setField("newPassword", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label></div>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<button disabled={saving} className="h-11 w-full rounded-xl bg-ink text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save profile"}</button></form>;
  if (session?.user.role === "EMPLOYEE") return <div className="mx-auto min-h-screen max-w-lg bg-slate-50 pb-24"><EmployeeHeader /><main className="px-5"><p className="text-sm text-slate-500">Account</p><h1 className="mt-1 text-2xl font-bold">Your profile</h1><div className="mt-6">{fields}</div></main><BottomNav /></div>;
  return <DashboardShell title="My profile"><p className="-mt-5 mb-6 text-sm text-slate-500">Manage your account details and password.</p>{fields}</DashboardShell>;
}
